
import type { Product, Order } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Radiant Glow Serum',
    description: 'A potent vitamin C serum to brighten and even out skin tone, leaving your skin with a radiant glow.',
    price: 3599,
    originalPrice: 4799,
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 35,
    category: 'Skincare',
    brand: 'Glow Beauty',
    tag: 'Save NRS 1200',
    rating: 4.8,
    reviewCount: 234,
  },
  {
    id: '2',
    name: 'Velvet Matte Foundation',
    description: 'Full-coverage foundation with a velvety matte finish that lasts all day without caking.',
    price: 3850,
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 25,
    category: 'Makeup',
    brand: 'CoverLuxe',
    rating: 4.5,
    reviewCount: 189,
    tag: "New"
  },
  {
    id: '3',
    name: 'Crimson Kiss Lipstick Set',
    description: 'A luxurious, highly pigmented lipstick in our signature crimson shade with a satin finish.',
    price: 4199,
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 50,
    category: 'Makeup',
    brand: 'Color Pop',
    rating: 4.9,
    reviewCount: 456,
  },
  {
    id: '4',
    name: 'Hydrating Hair Masque',
    description: 'Deeply conditioning hair masque to restore moisture and shine to dry, damaged hair.',
    price: 3200,
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 30,
    category: 'Haircare',
    brand: 'Silken Strands',
    rating: 4.6,
    reviewCount: 120,
    tag: 'Premium'
  },
  {
    id: '5',
    name: 'Midnight Bloom Perfume',
    description: 'An enchanting floral perfume with notes of jasmine, tuberose, and sandalwood for a captivating scent.',
    price: 7500,
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 22,
    category: 'Fragrance',
    brand: 'Mystique Scents',
    rating: 4.7,
    reviewCount: 98,
  },
  {
    id: '6',
    name: 'Gentle Cleansing Foam',
    description: 'A soothing micellar water that effectively removes makeup and impurities without stripping the skin.',
    price: 2279,
    originalPrice: 2759,
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 40,
    category: 'Skincare',
    brand: 'Clean & Co',
    tag: 'Save NRS 480',
    rating: 4.5,
    reviewCount: 123,
  },
   {
    id: '7',
    name: 'Anti-Aging Eye Cream',
    description: 'Revitalizing eye cream to reduce dark circles and fine lines.',
    price: 5519,
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 15,
    category: 'Skincare',
    brand: 'Youth Labs',
    rating: 4.7,
    reviewCount: 89,
    tag: "Premium"
  },
  {
    id: '8',
    name: 'Illuminating Highlighter',
    description: 'A powder highlighter for a radiant, buildable glow.',
    price: 2759,
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 60,
    category: 'Makeup',
    brand: 'Radiant Beauty',
    rating: 4.8,
    reviewCount: 167,
  }
];

export const mockOrderHistory: Order[] = [
  { 
    id: 'HIST_ORD001', 
    status: 'Delivered', 
    totalAmount: mockProducts[0].price + mockProducts[2].price + 50, 
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), 
    items: [{...mockProducts[0], quantity: 1}, {...mockProducts[2], quantity: 1}],
    shippingAddress: { street: '123 Old St', city: 'Pastville', state: 'OS', zipCode: '00001', country: 'Old Country'},
    trackingNumber: 'TRACKHIST001'
  },
  { 
    id: 'HIST_ORD002', 
    status: 'Shipped', 
    totalAmount: mockProducts[1].price * 2 + 50, 
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), 
    items: [{...mockProducts[1], quantity: 2}],
    shippingAddress: { street: '456 Past Ln', city: 'Memorytown', state: 'ML', zipCode: '00002', country: 'Old Country'},
    trackingNumber: 'TRACKHIST002'
  },
];
